### ISSUE TITLE
Crash with enquiry on Spatialite layer with null attributes

### ISSUE THREAD

**Issue by mesajs** [geopaparazzi/geopaparazzi#219]
To reproduce:
1. Load a spatialite layer where some of the features (rows) have nulls in some of the attributes (columns). Note: geometry is always present (not null).
2. Perform an enquiry on a feature where all attributes contain values. Works as expected.
3. Perform an enquiry on a feature some attributes contain NULL. GeoPaparazzi crashes.

Using GeoPaparazzi 4.0.1 on Sony Xperia Z3 Compact (Android 4.4.4)

**Comment by mj10777** [comment]
Geopaparazzi checks for geometries that are not NULL
* and will not load them

Other fields are read for possible label support
* no checking for NULL is done on these fields
   * this would be very **extensive** correction work for the Database
      * which is **not** the task of Geopaparazzi

There are Methods for correction of Geometries, since the displaying of Geometries is a majoor task of Geopaparazzi
* but otherwise it up to the user to supply a valid Database

Reason: 
* in general it is desired to leave the Database alone
   * since it is the property of the user
* in reality, settings are stored inside the Database as configuration options in extra tables
   * which can be removed easily **without** damage to the user data
* corrections for the SpatialIndex, UpdatelayerStatistics etc.
   *  are offered, to make the display - of otherwise unshowable geometries - possible
      * they must be activated by the user explicitly
         * since it is his/hers property being changed

It is therefore, **strongly**, suggested to something in the form of the following
* before finalising a Database for prodution use:

```sql
UPDATE table_name SET field_integer=0 WHERE field_integer IS NULL;
UPDATE table_name SET field_double=0.0 WHERE field_double IS NULL;
UPDATE table_name SET field_string='' WHERE field_string IS NULL;
```
Geopaparazi is designed for a specfic purpose
* anything hindering this purpose will be avoided
   * in this specfic case: becoming a general Database Administration tool

Any Application, using an external Database as information source
* cannot be expected to administer that external source

For these reason, I doubt that this problem can be resolved from inside Geopaparazzi
* and this must **remain** the task of the user that has supplied this external source

Mark

**Comment by moovida** [comment]
@mesajs , while Mark is probably right, I am wondering if I can somehow at least act in a defensive way. Since I am right now preparing the next release, could you supply me such a database to reproduce the problem?

**Comment by mj10777** [comment]
If this is to be considered and a sample database supplied
* then the important question would be
   * where does the application crash?
      * during the loading of the Map-Manager or
      * when displaying lables in the map-view

If the **second** is only true
* then (as with the geometry correction modus)
   * a special check could be turned on, so that at the next restart
      * every colum in every table in every database
         * where the table has at least on geometry a:
            * `SELECT count(colum_name) FROM table_name WHERE colum_name IS NULL`
   * and **turned off** after compleation

If the **first** is true
* then the above check would have to be done at every start
   * this would **slow** things down greatly

**Comment by moovida** [comment]
Thanks Mark, I also was wondering were things happen. I was up to just have a look and see if it is a simple thing somewhere to fix. Let's see if I get an db in time to reproduce the crash.

**Comment by mj10777** [comment]
While shopping just now, a simple solution accured to me
* assuming this crash happens while displaying the label-value

If I remeber correctly
* where the sql to select the geometry is done
   * when label should be shown
      * there is a simple adding of `,label_field_name` to the sql string
         * this could be replaced with:
            * `,CASE WHEN layer_field_name IS NULL THEN '' ELSE layer_field_name END`

Even if this is **not** the cause of the present problem
* this change would be advisable

**Comment by mesajs** [comment]
Thanks for your comments.

Most things work with a layer containing NULL's. The maps opens and features are displayed correctly. You can even set the label to display a NULL value (the feature displays correctly, but no label appears beside it).

The crash only occurs when the enquiry tool is employed, and a feature with a null attribute is selected. 

I can't agree that null values mean an invalid database - just that a value is unknown at present (and needs to be filled in when the value is known). These layers are successfully handled by QGIS, Geoserver and client side software such as OpenLayers.

**Comment by mesajs** [comment]
Opps, didn't mean to close

**Comment by moovida** [comment]
I agree. Again, can you supply a database to reproduce the problem?

**Comment by mesajs** [comment]
Here is a copy of the crash error message:
APP_VERSION_CODE=62
APP_VERSION_NAME=4.0.1
ANDROID_VERSION=4.4.4
PHONE_MODEL=D5833
CUSTOM_DATA=
STACK_TRACE=java.lang.RuntimeException: An error occured while executing doInBackground()
	at android.os.AsyncTask$3.done(AsyncTask.java:300)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:841)
Caused by: java.lang.NullPointerException
	at eu.hydrologis.geopaparazzi.maptools.FeatureUtilities.buildWithoutGeometry(FeatureUtilities.java:123)
	at eu.hydrologis.geopaparazzi.maptools.tools.InfoTool$1.doInBackground(InfoTool.java:238)
	at eu.hydrologis.geopaparazzi.maptools.tools.InfoTool$1.doInBackground(InfoTool.java:215)
	at android.os.AsyncTask$2.call(AsyncTask.java:288)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	... 4 more
java.lang.NullPointerException
	at eu.hydrologis.geopaparazzi.maptools.FeatureUtilities.buildWithoutGeometry(FeatureUtilities.java:123)
	at eu.hydrologis.geopaparazzi.maptools.tools.InfoTool$1.doInBackground(InfoTool.java:238)
	at eu.hydrologis.geopaparazzi.maptools.tools.InfoTool$1.doInBackground(InfoTool.java:215)
	at android.os.AsyncTask$2.call(AsyncTask.java:288)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:841)
 LOGCAT=--------- beginning of /dev/log/main

I now have to work out how to upload the database to github.  I tried responding to the email from github with the file attached but that did not seem to work. Perhaps I need to email it to you directly?

**Comment by mesajs** [comment]
Andrea. Have emailed database to you.

**Comment by moovida** [comment]
I have looked into this and I am not sure what the solution is. I hoped it would be clearer.

The problem is that we need to know the column data type  so that we can present proper tools for different types in cases editing is necessary. So far so good. 

In fact the column type I get when a value is NULL, is not of the type of the column, as for example TEXT for the comments field, but instead a value 5, which is the type NULL.

This doesn't help and I am a bit puzzeled, but I suspect this is due to the fact that sqlite stores the data not always in the type that is defined, but what it prefers to.

If someone has ideas, they are welcome.

For now I have created a workaround in setting NULL types always to the type TEXT. This will always work when querying layers, since it is a safe conversion. 
I am not sure what might happen if we try to insert a value into a field, which was NULL before and NOT of the type TEXT. In that case the insert query will add the quotes around the value and I am not sure if sqlite will then take care of converting.

This will need to be investigated, but at least for read-queries, it will work.

**Comment by mj10777** [comment]
SpatialVectorTable.getTableFieldType(fieldname)
* will return the determined (and cleaned up) datatype

With cleaned up is ment
* TEXT will be used for things line 'VARCHAR', 'VARCHAR[255]'
* INTEGER instead of INT INT8 etc

This is done which reading the database and collecting the fields

**Comment by moovida** [comment]
Amazing @mj10777 , this solved it, thanks.
Solved for next release.

**Comment by mesajs** [comment]
And the next release out already. That's quick!

Working beautifully now. Many thanks.
