### ISSUE TITLE
Unable to get local tile source to render tiles on map

### ISSUE THREAD

**Issue by surf9** [geopaparazzi/geopaparazzi#260]
Hi there

I've followed the information on the link below to try and use our own local tile source.

https://code.google.com/p/geopaparazzi/wiki/TileSources3#Custom_tiles_based_maps_%28local_and_remote%29

I was able to see the tile source definition I created from in the app. However, after selecting it my tiles are not rendered in the mapview.

Any ideas why this is failing? Do I need to use a container such as file extension map or mbtiles to get this working? If so what are some free tools I can use to help?

Thank you.

**Comment by moovida** [comment]
The wiki is now (kind of) maintained here: https://github.com/geopaparazzi/geopaparazzi/wiki#custom-tiles-based-maps-local-and-remote

We use STAGE to create mbtiles tile sources. The tiles folder is hard to handle with when there are many tiles.
More info here:
http://www.slideshare.net/silli/2014-10-27foss4gosakageopapworkshop

**Comment by surf9** [comment]
Thank you for your help.

**Comment by tghoward** [comment]
surf9, 
Since you asked within this thread and are still having some issues, I'll note that we are using landez to create mbtile datasets out of WMS sites. After some initial debugging for our specific target server, we are pretty happy with it.     

https://github.com/makinacorpus/landez

Cheers, 
Tim
