### ISSUE TITLE
Mbtiles file causes "ERROR: Index 0 requested, with a size 0"

### ISSUE THREAD

**Issue by surf9** [geopaparazzi/geopaparazzi#261]
Hi there

I'm just wondering why an mbtiles file created in qgis does not work in geopaparazzi?

I am getting the follow error message in geopaparazzi.

"ERROR: Index 0 requested, with a size 0"

The file works fine in qgis.

**Comment by mj10777** [comment]
Never having created a mbtiles with qgis, this was not tested.

I assume that this is done using gdal, which to my knowledge  worked without any problems.

To look into this further, I would need to know:
* what versions of;
   * qgis and gdal you are using

Also a small sample mbtiles, where this problem occurs, would be useful
* this would be **very** important, since the mbtiles code is very stable and no problems have been reported in more than a year

A short howto on how you create a mbtiles in qgis would save some time while looking into this.

**Comment by surf9** [comment]
Thanks for your response. Small correction. The MBTiles db was created via Mapcache, which adheres to the MBTiles spec:

http://www.mapserver.org/mapcache/caches.html#mbtiles-schema

The MBTiles db works happily in QGIS.

What is your email address to send the mbtiles db file? I cannot upload here due to not being an image.

**Comment by mj10777** [comment]
Sorry about the delay on this
* mj10777@googlemail.com

**Comment by mj10777** [comment]
Well, that was very simple:
* the `metadata` table is empty
   * this must be filled properly

It should look like this
* adapt as needed

```
name	Berliner Ortsteile
description	Darstellung der Ortsteile von Berlin. Quelle Stat. Landesamt. Erfassung auf dig. Blockkarte 1:5000
format	png
tile_row_type	tms
center	13.3777065575123,52.5162690144797,17
type	baselayer
version	1.1
bounds	13.0078125,52.21434020996094,13.886718749999988,52.69636154174805
minzoom	12
maxzoom	16
```

The wiki page:
* `https://github.com/geopaparazzi/geopaparazzi/wiki/.mapurl-parameters`
may help here

**Comment by surf9** [comment]
Thank you very much Mark! That solved my issue.
