### ISSUE TITLE
Spatialite 4.3.0 - License question

### ISSUE THREAD

**Issue by mj10777** [geopaparazzi/geopaparazzi#262]
Due to portions of spatialite that use GRASS GIS code, see:

https://www.gaia-gis.it/fossil/libspatialite/wiki?name=Affine+Transform
https://www.gaia-gis.it/fossil/libspatialite/wiki?name=Ground+Control+Points

any software using this functionality must use the **GPLv2+** license.

Since I have no idea about these licence questions, I will need to know how to deal with this.

To use this functionality, spatialite must be configured with
* ** --enable-gcp=yes**

If this poses no problem for geopaparazzi, I will use this option
* at the moment, however, I see no practical **need** to have it

Sandro has stated, that RasterLite2 is about 4/5 completed.

I will be keeping the Libraries up to date, so that when a final version 1.0 comes out, an extra geopararazzi could be offered with the bigger Libraries.
* no code changes would be needed - only the replacement of the Libraries

---

As to the splitting of the Overlay, I had tried this about a good year ago.
* removing the Geometry portion from `GeopaparazziOverlay.java`
* adding that to a 'GeometryOverlay'

and then adding in `MapsActivity.java`

```java
        dataOverlay = new ArrayGeopaparazziOverlay(this);
        List<Overlay> overlays = mapView.getOverlays();
        overlays.clear();
        overlays.add(dataOverlay);
        geometryOverlay = new GeometryOverlay(this);
        overlays.add(geometryOverlay);
```

at that time, I don't believe that there was a `ArrayGeopaparazziOverlay`, but only a GeopaparazziOverlay.
But it worked without a problem then as far as I remember. The priority then was in getting all of the changes into a stable form, so I left it to later - which left it to be forgotten.

**Comment by moovida** [comment]
Hi @mj10777, geopaparazzi is GPL3, so there should be no problem at all to work in that direction. 

Regarding the overlay part, the classes have been there since the migration to mapsforge. Right now I am not so keen to split the things in two, since I am not sure for how long we will stick to this version of mapsforge. Its community has been working a lot lately and many things have changed. So I would prefer to wait for a new release of mapsforge to migrate, if possible.
