### ISSUE TITLE
Clickable polygons for base layer and spatialite layer

### ISSUE THREAD

**Issue by surf9** [geopaparazzi/geopaparazzi#263]
Hi there

If I wanted polygons to be clickable from the mapview, so additional info can be displayed on the Android UI (not UI of mapview). What is the best way to get it working? Would that only work on spatialite db files or could that work for mbtiles db files?

I'd also like to query information about a polygon so I can find it's property info and ability to extract the area of a polygon excluding an area within it that potentially should not be calculated such as say a lake etc.

Any help appreciated.

**Comment by mj10777** [comment]
Answer to the mbtiles portion of the question:

It is a very bad idea to mix up the 2 different formats, although theoretically possible 
* assuming the reading program supports this.

Geopaparazzi does **not** support this.

It will first check if it a mbtiles file (during startup)
* and if not, check for `Vector` files that are supported.

It is an either or situation.

**Comment by surf9** [comment]
Hi Mark. Thanks for your input. Can you point me in the right direction for making a polygon clickable for both mbtiles and spatialite formats but only one active for listening on click events?

**Comment by mj10777** [comment]
This is a question that Andrea can answer in a more reliable way, but for it is worth:
* mbtiles is a Raster-Format and this has no Polygons (Vector)
* in the MapView the the functionality exist to display the properties of the show Geometries

Also, since Version 4.0, Polygons can be edited (but I have never used it, nor looked at the code)
* thus there would be something for the **selection** of the Polygon to change (I assume)
   * look for that

**Comment by tghoward** [comment]
@surf9, you do realize that spatialite layers already are clickable, right? You tap the edit icon (pencil) lightly, then touch the "i" (info) icon, then drag a box in the polygon or polygons from which you want to display the properties. 

Just checking to make sure. 
Tim

**Comment by surf9** [comment]
Hi Tim. I did not see that functionality. Thanks for clearing this up.
