### ISSUE TITLE
Datasource Button settings stored as use properties

### ISSUE THREAD

**Issue by mj10777** [geopaparazzi/geopaparazzi#272]
The 'Map', 'Mapurl', 'Mbtiles' and 'Rasterlite2' button settings should be stored
* so that when next used, this settings will be used
   * in my case this is mostly 'Rasterlite2' and pressing the first 3 off each time is a pain

**Comment by moovida** [comment]
as usual the things that seem easiest turn out to be a pain in the ass :-D
But it is done. Changed a bit the selection layout, also like it better now.

**Comment by mj10777** [comment]
This works correctly
* but I will be missing the buttons, which were nice
   * I was hoping they would either on or off

**Comment by moovida** [comment]
>
> This works correctly
>
>    - but I will be missing the buttons, which were nice
>       - I was hoping they would either on or off
>
> I also liked the buttons, but there were some problems:

* button doesn't seem to have the possibility to easily set its selection
status (I tried and looked for solution)
* togglebutton would work, but doesn't look decent with the buttons
backgrounds in geopap, hence a lot of other work to understand why.

After more than an hour I got fed up and changed this.

In fact it is better, because on small screens the names were too long and
if at some point a new type of datasource would be added, the space would
be too small anyways.
