### ISSUE TITLE
Geopackage support for the latest specification

### ISSUE THREAD

**Issue by surf9** [geopaparazzi/geopaparazzi#282]
Hi there

I'm just wondering if there will be support of the latest Geopackage specification in Geopaparazzi? Is it currently in development? If so, are you able to provide us a rough date when it will be ready?

Thank you for your help.

**Comment by mj10777** [comment]
At the moment I am refactoring the code that deals with all Vector/Raster types
* among them the Geopackage logic

Major Goal is to make the extension of the functionality offered easier
* mainly with `RasterLite2` in mind

So for the `GeoPackage_features` (Vectors/Geometries) portion
* full support can be expected soon

However, a full support for `GeoPackage_tiles` 
* is unlikely, since the GeoPackage-Tile logic is completely different 
   * the bounds of a Tile 
      * follows no standard rules as in tms/osm
* we would have to write code to
   * extract the needed tiles for the screen area to be shown
     * and piece them all together into one image
        * cutting out the portion needed for the screen

With RasterLite2
* the library does for us
   * we send the bounds and receive the resulting image

For `GeoPackage_features`
* the Spatialite-Library can return the GeoPackage-Geometries in the same format we need
   * thus no extra work

---
The major problem with `GeoPackage` is, in my option
* that they make up a lot of rules
   * but expect other to implement them

Where as `RasterLite2`
* the first major version expected in January 2016
   * make the rules
      * but also implements them
   * offers more functionality
      * full 1.1.0 SE/SLS Styles support
         * for both Vector and Rasters
   * with Sql-Queries everything needed by an Application can be retrieved

---
So:
* for `GeoPackage_features`
   * yes, very soon
* for `GeoPackage_tiles`
   * very unlikly

**Comment by surf9** [comment]
Hi Mark

Thanks for the thorough response!
