### ISSUE TITLE
Displaying tiles from two tile sources

### ISSUE THREAD

**Issue by npeihl** [geopaparazzi/geopaparazzi#286]
At our organization we use two tile sources for many of our maps. The base tile source is strictly aerial imagery. The second tile source is an overlay containing roads, labels, etc. which is placed over top of the aerial basemap. 

We do this because the aerial basemap never changes (obviously). But the overlay layer needs to be re-cached frequently.  If we were to merge the overlay and aerial imagery, re-caching would take a very long time. Re-caching just the overlay takes very little time.

Ideally we could display both tile caches are the same time in Geopaparazzi. Is it possible to add this as a feature?

Thanks.

**Comment by mj10777** [comment]
At the moment this (as 2 tile sources) is not possible
* we are using an older version of the mapsforge library that does not support this
   * the last version that supported **CustomTile**, that geopaparazzi needs

This support was removed from the **first** version of the newer mapsforge api
* but in the mean time has been **reintroduced**

About 2 months ago I made a first attempt in getting this to work
* but found that there were too many changes needed in areas of which I am not firm on
* also I could not get the mapsforge library itself to compile properly

So without a concentrated effort
* a swift switch-over to the present mapsforge library is unlikely in the near future.

The need to to so is, however, clear
* we would like to get the switching of maps from **inside** the Map-View working
   * this does not work in the present library
      * so we had to deactivate that in the present geopaparazzi code
* multiple layers (your request), I believe is supported
* and it is just a good idea to use the latest version
   * now that **CustomTile** is again being supported

I'm afraid it is a question of a lack in resources
* since there are only 2 of us actively working on this project
   * whereby I only deal with specific areas

---

end of part 1 of this answer

**Comment by mj10777** [comment]
For your specific situation
* there may be another solution in the short term, which may resolve your problems
  * `short` being 5-6 months 

---
**RasterLite2**
* a child project of Spatialite

this project is now in its final phase
* with the first release expected in January 2016

A RasterLite2 Database is contained inside a Spatialite Database
* so both Raster and Vector data are contained in one Database
   * but also SE/SLD 1.1.0 support for Styling

So one Database can contain:
* x number of maps (Raster)
* x number of geometries (Vector)
* x number of (single) Styles
   * which are either **Raster* or **Vector** specific
* x number of (grouped) Styles
   * containing a x number of references to the single Styles
* x number of references of which single/group Styles
   * should be applied to the Raster of Vectors

---
So if you have:
* one Raster (aerial)
   * intended as a background
      * a Style without transparency
* one Raster / Vector (roads, labels)
   * that will overlay the background
      * the Style defining the transparency needed
* a Group Style that combines the 2 single Styles

The final result should be a request
* where all of these Styles are applied
  * returning an image of the background with the overlaid image/vector

The modular buildup of this, is the cause of the delay of RasterLite2 release.

At the moment it is 4/5 complete
* but the development has been frozen 
   * due to the need to implement full Topology support for Spatialite
      * which should be completed in September
   * planned resumption is for November

---
end of part 2 of this answer

**Comment by mj10777** [comment]
For your Scenario you could have
* 1 Raster (aerial)
   * stored in one Database
      * since it does not change
* 1 Raster or Vector (roads, labels)
   * created in another database
      * when an update is needed

Note: 
* a `raster_coverage` 
   * can either be created from an
      * georeferences image (Geotiff, jpg with a world file)
      * directly from an WMS-Server
   * both are done from 1 Sql-command

* a `Master` Style-Database can be created
   * defined with all the needed Styles

---
A simple Sql-Script can be created that would
* create a new Database
* create the needed
   * spatial, rasterlite2 and style administration tables
      * each being a single Sql-Statement
* attach the 1st Raster (aerial) Database and
   * with one sql-command import the raster_coverage
* attach the 2nd Raster (roads, labels) Database and
   * import that raster_coverage
      * or geometry tables
* attach the Style Database and
   * import those Styles that are needed

When completed
* you will have a updated Database that can them be deployed

---
Although tools will be offered
* all of these tasks can be done with sql-commands
   * this be **automated** in a daily/weekly/monthly cycle as needed

---
end of part 3 of this answer

**Comment by mj10777** [comment]
RasterLite2 support in `geopaparazzi`

At the moment `geopaparazzi` supports RasterLite2
* without Style support

A version has been prepared with
* Style support
  * and works with simple/single styles applied
     * there you can see an image (right image) where
         * altitude colouring has been applied to a DEM file 

https://github.com/geopaparazzi/geopaparazzi/issues/281

This version is **patiently** waiting to be applied.

---
At the moment I am working on a historical Berlin RasterLite2-Database
* with at least 3 historical maps (1748, 1750 and 1811)
   * and if I receive permission, the first (2010) digital 1:5000 map
      * that was used to reference the above maps
* POLYGONS
   * showing the Sub-district borders seen on the 1811 map
* LINESTRING
   * showing the streets, bridges
      * with SpatialViews showing them based on the date
* POINTs
   * showing points of interest

---
The goal will be:
* a step by step documentation of the whole process
   * that will be stored here:

https://github.com/geopaparazzi/RasterLite2-Tasks/wiki/RasterLite2-Index

---
Once this exists
* the results can be tested in the RasterLite2 tools:
   * a mini wms server that can load the Database
   * a mini wms client that can view the Database
      * with the applied Styles

With that done
* to adapt `geopaparazzi`
   * to show the same results

**Comment by npeihl** [comment]
Hi @mj10777,

Thanks for all the info and suggestions. I've not heard of RasterLite2 before and may check it out when it has a full release. 

Geopaparazzi is already an incredibly useful app which I'm very happy with. Thank you for releasing it open source.
