### ISSUE TITLE
Form Tags GPS option

### ISSUE THREAD

**Issue by ravivundavalli** [geopaparazzi/geopaparazzi#293]
Geopaparazzi4. Unless the GPS is with a position a Form cannot be used. How ever inside the form you can select the form to be tagged with GPS or otherwise. Pl keep this option outside such that a Geologist can tag points away from the GPS easily, without standing in the sun for a GPS position every time he wants to tag a form.

**Comment by moovida** [comment]
That is not correct. Any note can be also placed in the center of the  map.
Please see the docs: http://geopaparazzi.github.io/geopaparazzi/main_view.html#notes

**Comment by ravivundavalli** [comment]
Andrea,
U R right, any note can be placed in the centre of the map.

BUT
As geologists we dont necessarily be in the sun (exposed to the heat) all
the time for a good GPS signal.

The form input only works when the GPS icon is green.
This only happens when you are under the sky and not in shade etc.
So we are not able to choose the 'Form input', without the GPS signal
working.

Hope I have made it clear pl.

Cheers
Ravi Kumar

**Comment by tghoward** [comment]
Ravi,
I can enter form data when the GPS icon is yellow, so we aren't sure what
you are saying. For example:
1. Start Geopaparazzi, no GPS signal
2. go to map view
3. touch 'forms' icon. The top button on the new screen reads "notes placed
in map center position" and you can't change it because there is no GPS
signal.
4. choose a form and enter data.
5. save it, return to map view.


So, for you, in the field, you can stand in the shade and place your cursor
(map center) at the location you want to collect the data (out in the sun)
and you should be able to begin a new form and enter data.

If you *can't*, then something is wrong and you should describe the problem
in more detail.

Does that help?
Cheers,

Tim
