### ISSUE TITLE
Compass requires non-free com.eclipsim.gpsstatus2

### ISSUE THREAD

**Issue by Matthias84** [geopaparazzi/geopaparazzi#303]
Hi,

geopaparazzi is distributed via www.f-droid.org even to Android compatible platforms as cyanogenmod, blackberryos, sailfishos, ... which works great. Unfortunatly the current version relies on a closed source extension (com.eclipsim.gpsstatus2) to read/display compas-information and embedd them as excif-tags.

I like to ask, if there are any plans to drop that third-party app and make use of open replacement, or add an compass to the original application?

**Comment by moovida** [comment]
Hi Matthias, thanks for opening this discussion.
Just a few comments:

1. We do not do any query to the gpsstatus app. The application is **only** opened by geopaparazzi, so that the compass is visualized. If the gpsstatus app is not installed, then no compass is shown, but the geopaparazzi application is fully functional. All gps and azimuth values work properly. Gpsstatus is used only for the user to view the compass.

2. I would be more than happy to use another, open source, application. I do not know any that works well and exposes an intent to open it from other apps. If you know a good one, I will be more than happy to replace it.

**Comment by Matthias84** [comment]
Hello @moovida and thanks for the hints. Indeed I was confused because of the prominent embedding of the app, but you are right, all information get recorded (not present in GPX but EXCIF and .properties).

If you consider to switch the linked compass application, I can recommend the following candidates of the F-droid store:
* [GetBack GPS](https://f-droid.org/repository/browse/?fdfilter=gps&fdid=com.github.ruleant.getback_gps)
* [SatStat](https://f-droid.org/repository/browse/?fdfilter=gps&fdid=com.vonglasow.michael.satstat&fdpage=2)
I guess it depends on the particular usecase which one is more helpful. I'm not familar with Android development, but maybe it's useful to add an pick dialog similar like 'open with'?

**Comment by moovida** [comment]
Hi @Matthias84 , thanks for the links to the projects, the SatStat looks great to me. 
I will look for an intent to run it and will then happily replace gpsstatus with that one. 
But I think the next release will not arrive before January.

**Comment by tghoward** [comment]
I agree SatStat looked like the better of the two for this purpose, but it
made me nervous that programming on it has not been touched for over a
year. Do you think updates with new versions of Android will be ok?

**Comment by moovida** [comment]
This has now been changed to use gps test, which is the only nice open source app that I found to also be on play.
