### ISSUE TITLE
WMS problem - Trento WMS gives white tiles

### ISSUE THREAD

**Issue by luca76** [geopaparazzi/geopaparazzi#353]
Hi, I cannot use this WMS server:

  http://webapps.comune.trento.it/ogc/

when I click "Import" and "WMS", I can see the available layers, but I cannot import anything.

**Comment by moovida** [comment]
Hi Luca, when I go on http://webapps.comune.trento.it/ogc/, I get a 

```
Not Found

The requested URL /ogc/ was not found on this server.
```

**Comment by luca76** [comment]
Sorry. The right url is:

  http://webapps.comune.trento.it/ogc

(without the trailing / )

**Comment by moovida** [comment]
Ups, ok, I now got it working placing the following getcapabilities url:
http://webapps.comune.trento.it/ogc?REQUEST=GetCapabilities

It loads all the layers and I can select them, but then, once I load that layer (tried ortofoto2015) the downloaded tiles are white. 

Not sure where the problem is. Will keep this ticket open for this problem to be solved.

**Comment by moovida** [comment]
fixed at last
