### ISSUE TITLE
notes and tags.json

### ISSUE THREAD

**Issue by tghoward** [geopaparazzi/geopaparazzi#410]
I've got two things that make working with json in the tags.json file a bit difficult:
1. If I want two complex but completely different forms (notes), I still need to stack the json all into the same tags.json file.
2. If I want a large list for the user to choose from, the entire list needs to be in tags.json, AND the entire list seems to be recorded with every record in the sqlite db.

Possible solutions?
1. Can there be a master tags.json file that points to different json files for different notes/forms. Background code would essentially insert the json code from the child files into the parent (tags.json) file?
2. Could the json file point to a lookup table (in json format?) that doesn't necessarily have to be inserted into the single field with all the other data?

Just some thoughts I've had while building some pretty complex notes. Thanks for considering or thinking about this.

**Comment by moovida** [comment]
```
If I want two complex but completely different forms (notes), I still need to stack the json all into the same tags.json file.
```
I agree this could be indeed something to work on. But honestly I think this is more an issue around the fact that there is no easy interactive gui to create/edit such form files. If that was available, i don't think many would have issues with what is inside.

```
If I want a large list for the user to choose from, the entire list needs to be in tags.json, AND the entire list seems to be recorded with every record in the sqlite db.
```
While this could be optimized (it gets a real pain when it comes to combos connected 1 to many), the fact that the whole form **section** (only the part related to the button) is placed into the database. While this is thick, I still believe it is strategic, because it allows to have notes opened and modified that do not exist inside you currently loaded tags anymore. I.e. the note can live on and maintains all the info it needs to be viewed and edited, if necessary.

**Comment by tghoward** [comment]
Ok, that reasoning make sense to me. Thanks for the reply!
