### ISSUE TITLE
ID tool registering different location when zoomed

### ISSUE THREAD

**Issue by tghoward** [geopaparazzi/geopaparazzi#450]
I love the extra-zoom-on-long-click enhancement discussed here: https://github.com/geopaparazzi/geopaparazzi/issues/351 but it does not seem to be accounted for when using the selection tool for viewing attributes for spatialite layers.  
To reproduce:
- load any basemap
- load any vector layer that has attributes
- zoom in to a high zoom level, but where some features of the vector layer are visible
- zoom in further while remaining at the current zoom level by long-pressing the + button. Do it a couple of times. 
- Press the pencil, press the dotted box, drag a box to identify a feature. I generally get the incorrect results. 

Tim

**Comment by moovida** [comment]
HI Tim, yes you are right, this has not been taken care of. It has been reported already bound to panning, since also the pan is affected by this wild hack, which is done by simply scaling the canvas. 

I am afraid this will be left like that, because I am planning to do a rendering engine change in hopefully near future. I am still hoping to be able to use nasaworldwind for android (at the time they do not support mercator tiles, i.e. our basemaps, but promised they would), and if not, use the new version of mapsforge.

So right now, given the low resources we are having on geopaparazzi, this issue will not be addressed.
Sorry
