### ISSUE TITLE
Profile color is used only if a Project is attached

### ISSUE THREAD

**Issue by brentfraser** [geopaparazzi/geopaparazzi#483]
A Profile's color is used for view's background color only if there is a Project attached to the Profile,  And the Create/Load project options are removed from the Main Menu.

**Comment by moovida** [comment]
That one is a feature, not a bug :-) I.e. it is doing what I thought it should.

* Color the main view if the main part, i.e. the project, is forced
* Remove any possibility to load or create a new project. 

We are working in a profile that is forcing you to use a project, so I am convinced the user should not be able to change it. If he needs to, then disable the profile, because it doesn't make sense.

Projects are exclusive, not as datasets are. So I think this is  how it should work.

**Comment by brentfraser** [comment]
So if I activate a Profile (and it has no project), the only way to use a Project is to go back add it to the Profile?

**Comment by moovida** [comment]
Oh, no, if there is no project, then everything should be enabled. No color and all project loading should be there. If it doesn't then it is a bug.

**Comment by moovida** [comment]
This is related to #485 and has been fixed.
