### ISSUE TITLE
Keyboard hides half of device screen - using back key to hide keyboard

### ISSUE THREAD

**Issue by AndrewM-** [geopaparazzi/geopaparazzi#510]
When the keyboard is up, it hides the fields in the lower part of the screen.  I have been using the back button (beside the home button below the screen of the phone/tablet) to make the keyboard go down after entering text in a field.  In effect, the back button has become the enter key for accepting data entries in form fields.  I wonder if this is causing me problems.  One user finds using the back key this way to be dissonant/weird.  Can you please clarify if this usage is correct.

I have also been creating forms with lots of sections, each with between 1 and 3 controls to reduce the effect of the keyboard covering things up.

**Comment by brentfraser** [comment]
The data entry portion of the form is scrollable (not obvious!), but perhaps we could make that scrollable portion bigger when the virtual keyboard is shown so it uses the top half of the screen instead of the just the middle portion.

**Comment by tghoward** [comment]
I actually made that change (increase window size of lower portion of form) in my fork, here:

https://github.com/tghoward/geopaparazzi/commit/1b645404c579697cde1f896997dd61240f2bee84

(at least I *think* that's the spot and the commit!)  I didn't try submitting as a pull request because I wasn't sure it would be a universal desire. 

Also, note that if you turn your gadget to landscape mode, the form view might be easier for data entry. 

Tim

**Comment by moovida** [comment]
I agree with @tghoward here. The nature of the forms makes them usable in a friendly way in landscape mode.
On smaller devices in portrait mode teh user experience is in general bad. The right thinh to do here would be to have a view with the sections and when tapping on a section the parameters view opens. Well, one of the many things that would be great to have. I think I refrained from doing the change last time because the complexity was huge due to the automatically generated form portions that have no references to the container.

If changing the weight makes portrait mode more usable, we should do it. Just let me know, I never use it in that mode.

**Comment by tghoward** [comment]
@AndrewM- Because the keyboard is a native Android feature the way to minimize the keyboard is by using another native Android feature: the back button. So think of it that way, you are using the back button to minimize the keyboard, not as the "return" key in the data entry form. So, in that use (minimize keyboard), yes, it is normal and should not have any undesirable effects.  But you need to be *very* careful because if you then use the back button again to leave the form (by not pressing the save icon on the top), your data will be lost (I've learned that from experience!). 

Hope that helps. 
Tim

**Comment by moovida** [comment]
I have solved these two things by resizing layout as @tghoward proposes + when a user exits with the back button, he is prompted if he reall wants to do that. That should make it safe. Might be bothering for some, but I find it better than loosing data.

Done in a0b5b3fd
