### ISSUE TITLE
Making the ability to change base maps easier to find

### ISSUE THREAD

**Issue by AndrewM-** [geopaparazzi/geopaparazzi#515]
Would it be possible to see the layers icon in the cell phone version on the main menu page so that people who don't read well can just touch the icon? I have both tablet and phone and they are slightly different.  The icon I referring to is the two stacked layers on the left of the image below.

![2018-06-05_basemapicon](https://user-images.githubusercontent.com/5060805/40950918-17db639e-68b8-11e8-8b6f-ed8a04f24c80.png)

**Comment by brentfraser** [comment]
Some of the icons are shown "if there is room" on the action bar.  Try turning the phone sideways,  Can you explain more about "so that people who don't read well can just touch the icon".  I don't understand that part.

**Comment by moovida** [comment]
I see @AndrewM- point. Right now on the phone the settings button is visible, while the tiles button is not. 
Moreover I still enter the menu to look for the settings to notice that it is the icon outside. 

So I would be very happy to reverse those two in order to have the tiles button always visible and the settings in the menu.

**Comment by moovida** [comment]
Done, tiles button is visible now
