### ISSUE TITLE
Hints for the type of information that needs to be entered into each control

### ISSUE THREAD

**Issue by AndrewM-** [geopaparazzi/geopaparazzi#525]
When working with people who are learning to undertake surveys, it is common for them to forget what to put in a form field.  For example, "Distance" is a field in one of my recent forms.  I am using the trip odometer on a Garmin GPS to get a distance from the start of the weed survey.  If I could enter a hint such as 'trip odometer reading from Garmin GPS", that would help.  Currently the guys carry laminated paper sheets which provide the hints.  We also get a lot of staff turn-over so system need hints.

As an aside, where our sampling design requires navigation, we will probably continue to use Garmin GPS units as they are good for this.  Geopaparazzi is almost feature complete and we will not be recommending extension of the feature set into non-core areas.

**Comment by tghoward** [comment]
I use the "labels" feature to provide hints. You just add a label before the field (it can even be in a different size font) with the instructions on how to enter data in the field or to otherwise define the field. You can also use this for instructions for different sections, etc. 

http://geopaparazzi.github.io/geopaparazzi/#_labels

Also, remember that the "key" (which would be a column name after exporting) can be different than the "label"  (which is what the user sees on the form, associated with the field). 

Hope that helps. 
Tim

**Comment by AndrewM-** [comment]
Thanks Tim, I have picked up on this and implemented in my forms designer.

**Comment by moovida** [comment]
It seems this can be closed.
