### ISSUE TITLE
Swaping tile source with map scale

### ISSUE THREAD

**Issue by AndrewM-** [geopaparazzi/geopaparazzi#528]
My operational area is about 500 km across and is 68 000 square kilometres.  In terms of map tiles, I need to cover scales from 10-17 and in the future, I might like to extend down to about 20.  Currently, use an aerial image for levels 14-17 and a scanned topographic map for scales 10-14.  Would it be possible to list more than one tile source and to have geopaparazzi switch from one to the other depending on scale?  The layers could be ranked so that the higher rank draws first if the tiles sources overlap in levels.  

I just get lost sometimes when the background map disappears.  This might occur when I zoom in on the start of a gps trail using function provided in the edit notes list.

**Comment by moovida** [comment]
I see this very difficult to achieve with the current rendering engine. The next generation will sure support multilayers.

**Comment by brentfraser** [comment]
@AndrewM-  Perhaps you could create a single MBTiles dataset combining the two rasters.  Using GDAL's gdal_translate (or gdal_warp?) to convert the rasters to MBTiles.

**Comment by tghoward** [comment]
@brentfraser that's a good idea. Landez will also composit different sources into a single mbtiles database:

https://github.com/makinacorpus/landez

**Comment by AndrewM-** [comment]
I suspect that mbtiles requires all of the rasters to have the same extent.  If that is the case, then the approach of replacing some tile layers with data from another source will not work in my context.  I am hoping for the ability to have high level data for the whole region and detailed imagery only for areas on interest.  I think rasterlite 2 will help with this.  What I was hoping for is like how custom maps work in Garmin GPS units.  If you have two maps for the same area, the finer scale one shows when zoomed in and the wide area one shows when zoomed out.  The spatial coverage of each custom map can be different.

**Comment by mj10777** [comment]
>> I suspect that mbtiles requires all of the rasters to have the same extent.

No, this is not correct. The bounds must reflect the maximum extent of all the Zoom-Levels.

>> I am hoping for the ability to have high level data for the whole region and detailed imagery only for areas on interest.

This is possible for MbTiles, but not for RasterLite2.

---
**MBTiles**
A MbTiles Database can contain only 1 Raster-Layer (For RasterLite2: raster_coverage)
The bounds value must/should reflect the  maximum extent of all the Zoom-Levels so that the Reader will know if it should attempt to retrieve data for a specific area.

A MbTiles-Raster-Layer will contain multiple Zoom-Levels.
Rarely does the Reader check if the lower (more detailed) Zoom-Level is completely filled.
In most cases, it will look for the requested area and if nothing is found return an empty Image.

A reader **never** checks if the lower level contains the same source as a higher (less detailed) Zoom-Level.
So it is possible to mix the Zoom-Levels with different image sources.

So in this way, you could create a MBTiles Database:
* Zoom-Levels 0-3: Blue-Marble of the whole World
* Zoom-Levels 4-5: some more detailed source for Europe (leaving everywhere else empty)
* Zoom-Levels 5-8: some more detailed source for Italy and Ireland (leaving everywhere else empty)
* Zoom-Levels 9-16: some more detailed source for Regions/Counties in Italy and Ireland (leaving everywhere else empty)
* Zoom-Levels 17-20: very detailed area for project areas of interest (leaving everywhere else empty)

It is up to the MbTiles creator to fill the Database with the needed tiles.
* most readers **should** return an blank image if nothing is found

Care should be taken, so that the user does not get lost in a 'white sea of tiles' (i.e in the next higher level contains images to that the user can find the area it is looking for).

---
**RasterLite2**
Can contain more than 1 Raster-Layer called 'raster_coverage'.
Each Raster-Layer is created from 1 images source, where a **internal** set of tiles, in the original resolution, is created.
On demand, an Image (that can be of a lower/higher resolution) is created from this set of  **internal** tiles.
This is why a Raster-Layer **cannot** be created from different images of  different resolutions.

---
**MbTiles** : will always be in World Mercator, EPSG:3857 - with the bounds values in Wsg84, EPSG:4326

**RasterLite2**: will always use the SRS of the original image. Image area requests must, therefore, be transformed into that SRS.
