### ISSUE TITLE
status of Geopackages?

### ISSUE THREAD

**Issue by brentfraser** [geopaparazzi/geopaparazzi#540]
I see there is a lot of code in Geopaparazzi to handle Geopackages.  Are there any tests, doc, workflows on it?

**Comment by mj10777** [comment]
Not really.

The minimal GeoPackage support (Vector only) is part of the general sqlite3 Database reading logic where it is determined what type of Database is being read.

Mainly:
* Spatialite
* RasterLite2
* MbTiles
* GeoPackage

The main documentation for this is at:

https://github.com/geopaparazzi/Spatialite-Tasks-with-Sql-Scripts/wiki

At some point, this code was re-fractured with the goal of simplifying the many parameters form where the collected information was gathered to where the information was needed to render.

A general Object was created and filled, so that in the many,many,many intermediate functions only this Object would be passed through, instead of dozens of parameters as it still is today.
This also removed the multible checks done in many different functions instead of one central area, making the code difficult to maintain and a horror to extend.

This was mainly done to fully support the possibilities that RasterLite2 will offer, without changing each and every intermediate function between the collection and rendering.

The refracting was rejected and with that my active development ended.

**Comment by AndrewM-** [comment]
I have moved to 100% geopackage use in QGIS as it is the default with QGIS 3 so I would certainly value Geopackage support.

**Comment by brentfraser** [comment]
We should put together a demo data set showing each of the supported formats. I guess the Geopackage format is not technically supported since it is not documented (yet?).

**Comment by mj10777** [comment]
See my comment from July 7.
Only geometries are supported.

**Comment by moovida** [comment]
Ahhh, sorry, you are right. The rasterlite2 packages work as tiles. I confused this. Apologies.
