### ISSUE TITLE
GPS Log rendering not using set symbology

### ISSUE THREAD

**Issue by brentfraser** [geopaparazzi/geopaparazzi#558]
If I start a GPS log, change the symbology, leave the Map View (add note, back to Main view, etc) then return to Map View, the start and stop log locations are shown.   Even though the log has not been stopped, the stop location is shown as the location when I left the Map View screen.  The log track line continues from this point but does not use the symbology I set.
![screenshot_1534193631](https://user-images.githubusercontent.com/1638313/44420571-86eafa00-a53b-11e8-9ed1-55fc11663416.png)
 I expected that no stop position would be shown since I had not stopped the log, and the entire track would be in the symbology that i had set.

The reason this is important is to ensure the user that GPS logging has not been automatically stopped for some reason.

**Comment by moovida** [comment]
I will check this, but if I remember the resaon correctly, it was done (many years ago) because I didn't want to make inside the rendering loop an additional query to get the id of the current recorded log, because oif peformance issues. 

I really do not like the start and end markes to be honest and would like to remove them. But they are handy many times... so I am not sure how to act on this.

**Comment by brentfraser** [comment]
I think having the start and stop symbols is fine, but the stop symbol should be shown only if the log has been stopped.  Currently is is shown even if the user leaves the Map View and returns.  This can be unsettling for new users who may be unsure if the logging is working.

Same for the line rendering.  We may need to look at the events to find a way to get the symbology with acceptable performance.

**Comment by moovida** [comment]
The problem here is the rendering system, which bases on the old mapsforge, which didn't have a real concept of layers and would easily go out of memory.

The whole vector spatialite part is pushed inside that engine, but is not really performant. To be honest I do not think that there is a lot of margin to do more things in there. I would rather be able to step to a new rendering system. But that one is far away right now.

**Comment by moovida** [comment]
Ok, I reviewed the code and it was simpler than I thought. I removed teh circle from the last log, if it was currently active in logging. Will test it on way home later.

Done in 8e10d011

**Comment by brentfraser** [comment]
Any hope the line rendering fix would be easy?

**Comment by moovida** [comment]
Not sure what you mean @brentfraser

**Comment by brentfraser** [comment]
The GPS track in the above image is shown with two types of symbology: the one assigned by the user (for the first part of the line), and the default (the second part of the line).  It would be best if the entire line was rendered with just the user assigned symbology.  The problem is shown when the user leaves the Map View the returns.  GPS data gathered after returning uses the default symbology even though it is in the same GPS log.

**Comment by moovida** [comment]
Ahh, got it. This has been done because the user could see which is the current active. If you have many logs, this would be confusing. the reason because the line is kept partial, is because that part is in memory and therefore can't be kept "infinite".

**Comment by brentfraser** [comment]
ok.  Is is possible to set the default rending values?  The narrow yellow can be hard to see in some outdoor cases.

**Comment by moovida** [comment]
I was thinking that we could place the internal color to the color of the line made by the user. And just add a "border line". That should kind of help and keep consistent. What do you think?
