### ISSUE TITLE
rearrange Layers List

### ISSUE THREAD

**Issue by brentfraser** [geopaparazzi/geopaparazzi#616]
As Project Layers will likely be used (turned on/off, etc) more often than Map Layers, put Project Layers on the left side of the screen (seen first).  And move the FAB button up a bit so the user can touch the item menu on the bottom item.

Make the Add Layer FAB shown only when viewing the Map Layers list and not when viewing the Project Layers list.

**Comment by brentfraser** [comment]
And remove the settings ellipsis from the Project Layer items until we add code to have them do something.

**Comment by moovida** [comment]
Removed ellipsis if no options are available

I do not agree that much on the proposed rearrange instead. I almost never touch the system layers, while I very often add and remove maps.

Regarding the FAB, it is not in the way on my devices:

![image](https://user-images.githubusercontent.com/390250/62852018-756ca600-bce8-11e9-9e09-c6e10da12a6e.png)

I am a bit reluctant to move the FAB only by a bit, because it is connected to the hidden FABs that appear when it is tapped and there it goes in pixels count. 
I would rather move it to the bottom middle. Would that help?

FAB hide/show also added as suggested.

**Comment by brentfraser** [comment]
I tend to use the Map Layer list more too (at least while testing and for updating the doc), so maybe the current arrangement is better.

Leave the FAB where it is; I was trying to press the ellipsis on the  "Map Scale Bar" while testing (it was hidden by the FAB), but since the ellipsis is removed (and the FAB is not shown for Project layers), it is not a problem.

**Comment by moovida** [comment]
Ok, great. Obviously feel free to reopn issues. I am closing them because otherwise I get depressed by the amount of work without proceeding :-D
