### ISSUE TITLE
Add opacity to .map file layers

### ISSUE THREAD

**Issue by brentfraser** [geopaparazzi/geopaparazzi#618]
You can set opacity on cloud tile layers, but not .map file layers

**Comment by moovida** [comment]
as fare as I know that is not possible. Also consider that all map files are bundled together into a single multi layer, in order to avoid boundary overlaps.

The layer sin general show only the options they have. Map files have 3D and labels for example, which others do not.

**Comment by brentfraser** [comment]
Hmm. OK.  Seems to limit the usefulness of .map files with other layers.  Maybe additional themes would help.  Is there a "buildings only" theme?

**Comment by moovida** [comment]
Why do you think it limits usefulness? There are different themes defined by vtm. They can be selected.

The buildings and labels layer are placed always as last on top, so that any additional layer covers the mapsforge one and has the buildings on top of it. Is that what you meant?

In future I can look a bit more in deep into VTM ad see what can be done with transparency, but right now it would be too much.

**Comment by brentfraser** [comment]
My hope was to use an imagery layer on the bottom, with a vector layer (.map) on top showing building shapes, road and other lines and points, but not land use polygons so the imagery would show through.  Transparency would be compromise of this.   Basically the iamge you tweeted:
![image](https://user-images.githubusercontent.com/1638313/62871683-2cf9bc00-bcd9-11e9-8614-cb771997e3b8.png)
