### ISSUE TITLE
Spatialite: allow labeling of Spatialite features on map

### ISSUE THREAD

**Issue by brentfraser** [geopaparazzi/geopaparazzi#623]

**Comment by moovida** [comment]
That is quite complex to achieve. We can leave this open here, but I will exclude this from the upcoming release.

**Comment by scott-emmons** [comment]
We use this feature in the present version of Geopaparazzi.  We are very excited to change to the new version (many great improvements), but we need the ability to label vector data (spatialite data) on the map.

**Comment by moovida** [comment]
Hi @scott-emmons , sorry for the late reply, was on vacation. This feature requires some work and we are currently leaving it behind for the next release, since we are missing resources for it. 
Would you have the possibility to contribute the changes yourself? I would be happy to wait for it if you say you could.

**Comment by moovida** [comment]
This has been solved. But given the issues with labelling the vtm engine and the extra layers it would have created, we had to work around it.

So to visualize labels you use a map button (which only appears if there are layers supporting labelling). On the bright side this works very well and it also has collision checks, so labels will always be readable. (check is done on the same layer only).

![animation](https://user-images.githubusercontent.com/390250/70859723-45dcdd00-1f18-11ea-827a-81402c87fbbb.gif)
