### ISSUE TITLE
The screen display of the latest version is dirty

### ISSUE THREAD

**Issue by sakuya-izayoi-0518** [geopaparazzi/geopaparazzi#655]
Developer
The mbtiles displayed by the latest version of the application are displayed more dirty than the mbtiles displayed by Version 5.X.
Is it possible to change the settings to return to the previous screen display?

English is not my native language, so I'm sorry for the poor writing.

**Comment by moovida** [comment]
This is due to the fact that the VTM rendering system works also outside the **exact** zoomlevels of the mbtiles schema. This is necessary to be able to have the 3D for sure.
So what you experience is probably blurry tiles when you are between 2 zoomlevels.

I am afraid there is not much that can be done about it. If you just use the zoom buttons to move between zooms, than this should not happen, since it chooses the right zoomlevels.
